import { ApexOptions } from "apexcharts";
import React, { useEffect, useState } from "react";
import ReactApexChart from "react-apexcharts";
import axios from "axios";

interface ChartThreeState {
  series: number[];
  days: string[];
}

const options: ApexOptions = {
  chart: {
    fontFamily: "Satoshi, sans-serif",
    type: "line",
  },
  colors: ["#3C50E0"],
  legend: {
    show: false,
    position: "bottom",
  },
  dataLabels: {
    enabled: false,
  },
  responsive: [
    {
      breakpoint: 2600,
      options: {
        chart: {
          width: 380,
        },
      },
    },
    {
      breakpoint: 640,
      options: {
        chart: {
          width: 200,
        },
      },
    },
  ],
};

const cities: string[] = [
  "A Coruña",
  "Aalborg",
  "Aaley",
  "Aalst",
  "Aarhus",
  "Aarsâl",
  "Aasiaat",
  "Aba",
  "Abadan",
  "Abengourou",
  "Abeokuta",
  "Abhā",
  "Abidjan",
  "Abomey-Calavi",
  "Abovyan",
  "Abu Dhabi",
  "Abuja",
  "Abéché",
  "Abū Dīs",
  "Abū Ţisht",
  "Abū Ḩulayfah",
  "Abū Ḩummuş",
  "Acarlar",
  "Accra",
  "Acharnés",
  "Aconibe",
  "Acquaviva",
  "Acıgöl",
  "Acıpayam",
  "Ad Dammām",
  "Ad Dirāz",
  "Ad Dīwānīyah",
  "Adaklı",
  "Adalar",
  "Adamstown",
  "Adana",
  "Adda-Douéni",
  "Addis Ababa",
  "Adelaide",
  "Aden",
  "Adh Dhakhīrah",
  "Adi Keyh",
  "Adilcevaz",
  "Adıyaman",
  "Afanyangan",
  "Afega",
  "Afyonkarahisar",
  "Afşin",
  "Agadez",
  "Agadir",
  "Aguadilla",
  "Aguadulce",
  "Aguascalientes",
  "Ahlat",
  "Ahmedabad",
  "Ahmetli",
  "Ahuachapán",
  "Ahvāz",
  "Aileu",
  "Ainaro",
  "Aioun",
  "Ajdābiyā",
  "Akbez",
  "Akdağmadeni",
  "Akhisar",
  "Akhmīm",
  "Akjoujt",
  "Akkuş",
  "Aksaray",
  "Akseki",
  "Aksu",
  "Aktepe",
  "Aktuluk",
  "Akure",
  "Akureyri",
  "Akyaka",
  "Akyazı",
  "Akyurt",
  "Akçaabat",
  "Akçadağ",
  "Akçakale",
  "Akçakoca",
  "Akşehir",
  "Ak’ordat",
  "Al Aḩmadī",
  "Al Bayḑā’",
  "Al Başrah",
  "Al Buraymī",
  "Al Fashn",
  "Al Fayyūm",
  "Al Fujayrah",
  "Al Hamalah",
  "Al Hufūf",
  "Al Jahrā’",
  "Al Jazīrah al Ḩamrā’",
  "Al Jubayl",
  "Al Jumayl",
  "Al Jumaylīyah",
  "Al Juwayyidah",
  "Al Jīzah",
  "Al Khawr",
  "Al Khubar",
  "Al Khums",
  "Al Kūt",
  "Al Madrah Samā’il",
  "Al Mafraq",
  "Al Manāqil",
  "Al Manşūrah",
  "Al Manşūrah",
  "Al Marj",
  "Al Maḩallah al Kubrá",
  "Al Ma‘allā’",
  "Al Mijlad",
  "Al Mubarraz",
  "Al Mukallā",
  "Al Muḑaybī",
  "Al Muḩarraq",
  "Al Mālikīyah",
  "Al Qaţīf",
  "Al Qunfudhah",
  "Al Qurnah",
  "Al Qāmishlī",
  "Al Wakrah",
  "Al Ḩajar al Aswad",
  "Al Ḩasakah",
  "Al Ḩillah",
  "Al Ḩillah",
  "Al Ḩişn",
  "Al Ḩudaydah",
  "Al ‘Amārah",
  "Al ‘Aqabah",
  "Al ‘Ayn",
  "Al ‘Āmirāt",
  "Alaca",
  "Aladağ",
  "Alajuela",
  "Alanya",
  "Alaplı",
  "Alaçam",
  "Alaçatı",
  "Alaşehir",
  "Albina",
  "Alcalde Díaz",
  "Aleg",
  "Aleppo",
  "Alexandria",
  "Algiers",
  "Ali Sabieh",
  "Aliağa",
  "Alicante",
  "Allada",
  "Almada",
  "Almaty",
  "Almere",
  "Almus",
  "Alofi",
  "Alotau",
  "Alpu",
  "Altay",
  "Altunhisar",
  "Altındağ",
  "Altınekin",
  "Altınova",
  "Altıntaş",
  "Altınyayla",
  "Altınözü",
  "Alucra",
  "Alytus",
  "Am-Timan",
  "Amadora",
  "Amasra",
  "Amasya",
  "Amatitlán",
  "Ambato",
  "Ambilobe",
  "Ambohimangakely",
  "Ambovombe",
  "Amersfoort",
  "Amman",
  "Amsterdam",
  "An Najaf",
  "An Nāşirīyah",
  "Anamur",
  "Ancón",
  "Anderlecht",
  "Andijon",
  "Andorra la Vella",
  "Androtsy",
  "Andırın",
  "Angers",
  "Angren",
  "Anju",
  "Ankara",
  "Ankazoabokely",
  "Anna Regina",
  "Annaba",
  "Anouvông",
  "Ansan",
  "Antalaha",
  "Antalya",
  "Antananarivo",
  "Antehiroka",
  "Antipolo",
  "Antofagasta",
  "Antsirabe",
  "Antsiranana",
  "Antwerp",
  "António Enes",
  "Anyang",
  "Aného",
  "Apeldoorn",
  "Apia",
  "Aplahoué",
  "Apopa",
  "Aqtaū",
  "Aqtöbe",
  "Aquin",
  "Ar Ramthā",
  "Ar Ramādī",
  "Ar Raqqah",
  "Ar Rayyān",
  "Ar Riqqah",
  "Ar Ruseris",
  "Ar Rustāq",
  "Ar Ruşayfah",
  "Araban",
  "Arad",
  "Aradíppou",
  "Arafat",
  "Araklı",
  "Aralık",
  "Arapgir",
  "Ararat",
  "Aravan",
  "Arawa",
  "Araç",
  "Arcahaie",
  "Ardabīl",
  "Ardahan",
  "Ardeşen",
  "Arecibo",
  "Areguá",
  "Arendal",
  "Arequipa",
  "Arhavi",
  "Ariana",
  "Aribinda",
  "Arica",
  "Arifiye",
  "Arima",
  "Arlit",
  "Armavir",
  "Armutlu",
  "Arnavutköy",
  "Arnhem",
  "Arpaçay",
  "Arraiján",
  "Arroyo Naranjo",
  "Arsin",
  "Arsuz",
  "Arta",
  "Artashat",
  "Artigas",
  "Artik",
  "Artik",
  "Artvin",
  "Arusha",
  "Arvayheer",
  "Arıcak",
  "As Safīrah",
  "As Salamīyah",
  "As Salţ",
  "As Sulaymānīyah",
  "As Suwayq",
  "As Sīb",
  "Asarcık",
  "Asau",
  "Asenovgrad",
  "Ash Shajarah",
  "Ash Shaykh ‘Uthmān",
  "Ash Shiḩr",
  "Ash Shāmīyah",
  "Ash Shīḩānīyah",
  "Ashaiman",
  "Ashdod",
  "Ashgabat",
  "Ashmūn",
  "Ashqelon",
  "Ashtarak",
  "Asker",
  "Aslanapa",
  "Asmara",
  "Assab",
  "Assomada",
  "Astana",
  "Asunción",
  "At Tawāhī",
  "Atakpamé",
  "Atamyrat",
  "Atar",
  "Atebubu",
  "Athens",
  "Athurugiriya",
  "Atlanta",
  "Attapu",
  "Attard",
  "Attiecoubé",
  "Atyraū",
  "Auckland",
  "Auki",
  "Avanos",
  "Avarua",
  "Avcılar",
  "Aves",
  "Avrankou",
  "Avsallar",
  "Aw Dheegle",
  "Aweil",
  "Awka",
  "Ayacucho",
  "Ayancık",
  "Ayaş",
  "Aybastı",
  "Aydın",
  "Aydıncık",
  "Aydıncık",
  "Ayolas",
  "Ayorou",
  "Ayvacık",
  "Ayvacık",
  "Ayvalık",
  "Az Zarqā’",
  "Az Zubayr",
  "Az Zuwāydah",
  "Az Zāwīyah",
  "Az̧ Z̧a‘āyin",
  "Az̧ Z̧āhirīyah",
  "Añisoc",
  "Ağcabədi",
  "Ağlasun",
  "Ağrı",
  "Aş Şuwayḩirah as Sāḩil",
  "Aşağıçinik",
  "Aşkale",
  "Aţ Ţurrah",
  "Aţ Ţā’if",
  "Ba",
  "Baabda",
  "Baalbek",
  "Baardheere",
  "Babaeski",
  "Babahoyo",
  "Babruysk",
  "Bacoor",
  "Bacău",
  "Bade",
  "Baden",
  "Badou",
  "Bafatá",
  "Bafilo",
  "Bafoussam",
  "Bafra",
  "Bafut",
  "Bagam",
  "Baghdad",
  "Bago",
  "Baguinéda",
  "Bahawalpur",
  "Bahir Dar",
  "Bahlā’",
  "Bahçe",
  "Bahçesaray",
  "Bahía Blanca",
  "Bahār",
  "Baia Mare",
  "Baidoa",
  "Baie du Tombeau",
  "Bajos de Haina",
  "Bakau",
  "Bakouma",
  "Baku",
  "Bakıxanov",
  "Bala",
  "Balandougou",
  "Balboa Heights",
  "Balkanabat",
  "Balkh",
  "Ballarat",
  "Balya",
  "Balykchy",
  "Balzers",
  "Balçova",
  "Balıkesir",
  "Bamako",
  "Bambadinca",
  "Bambari",
  "Bambous",
  "Bamenda",
  "Ban Bang Pu Mai",
  "Ban Houayxay",
  "Ban Laem Chabang",
  "Ban Mangkon",
  "Ban Nong Prue",
  "Ban Talat Rangsit",
  "Banaz",
  "Bandar Lampung",
  "Bandar Seri Begawan",
  "Bandraboua",
  "Bandrele",
  "Bandırma",
  "Banfora",
  "Bangalore",
  "Bangar",
  "Bangassou",
  "Bangkok",
  "Bangui",
  "Banikoara",
  "Banja Luka",
  "Banjul",
  "Bansang",
  "Banská Bystrica",
  "Baní",
  "Banī Suhaylā",
  "Banī Walīd",
  "Baoding",
  "Bar",
  "Baranavichy",
  "Barcelona",
  "Barcelona",
  "Barentu",
  "Bargny",
  "Bari",
  "Bariadi",
  "Barinas",
  "Barquisimeto",
  "Barr Eliâs",
  "Barranquilla",
  "Barros Blancos",
  "Bartica",
  "Bartın",
  "Barura",
  "Basel",
  "Baskil",
  "Bassar",
  "Basse Santa Su",
  "Basse-Terre",
  "Basseterre",
  "Bassila",
  "Bat Yam",
  "Bata",
  "Batam Centre",
  "Batken",
  "Batman",
  "Batna",
  "Batroûn",
  "Battalgazi",
  "Battambang",
  "Batticaloa",
  "Batumi",
  "Baucau",
  "Bauska",
  "Bawshar",
  "Bayamo",
  "Bayamón",
  "Bayanhongor",
  "Bayat",
  "Bayat",
  "Bayburt",
  "Baykan",
  "Bayramaly",
  "Bayramiç",
  "Bayt Jālā",
  "Bayt Lāhyā",
  "Bayt Sāḩūr",
  "Bayt Ūmmar",
  "Baytūnyā",
  "Bayındır",
  "Bazal’tove",
  "Bazar-Korgon",
  "Bazimini",
  "Bağcılar",
  "Bağlar",
  "Başkale",
  "Başmakçı",
  "Ba‘qūbah",
  "Beersheba",
  "Beijing",
  "Beira",
  "Beirut",
  "Beitbridge",
  "Bejaïa",
  "Bekasi",
  "Bekasi Kota",
  "Bel Air",
  "Belas",
  "Beldibi",
  "Belek",
  "Belen",
  "Belfast",
  "Belgrade",
  "Belize City",
  "Bellinzona",
  "Bello",
  "Belmopan",
  "Belo Horizonte",
  "Belo Tsiribihina",
  "Belém",
  "Bender",
  "Bendigo",
  "Benghazi",
  "Bengonbeyene",
  "Benguela",
  "Benguema",
  "Benin City",
  "Bensonville",
  "Bené Beraq",
  "Berane",
  "Berat",
  "Berbera",
  "Berbérati",
  "Bereket",
  "Bergama",
  "Bergen",
  "Berlin",
  "Bern",
  "Bertoua",
  "Besni",
  "Bet Shemesh",
  "Bethlehem",
  "Betio",
  "Betsiboka",
  "Beydağ",
  "Beykoz",
  "Beylikdüzü",
  "Beypazarı",
  "Beyşehir",
  "Beşikdüzü",
  "Beşiri",
  "Bhaktapur",
  "Bharatpur",
  "Białystok",
  "Bibémi",
  "Bibā",
  "Biel/Bienne",
  "Bielefeld",
  "Bifoun",
  "Biga",
  "Bigadiç",
  "Bihać",
  "Bijeljina",
  "Bijelo Polje",
  "Bilbao",
  "Bilecik",
  "Bilwi",
  "Biləcəri",
  "Bimbo",
  "Bimo",
  "Bindura",
  "Bingerville",
  "Bingöl",
  "Bir el Djir",
  "Birecik",
  "Birgañj",
  "Birkirkara",
  "Birmingham",
  "Birnin Konni",
  "Birāṭnagar",
  "Birżebbuġa",
  "Bisee",
  "Bishkek",
  "Biskra",
  "Bismil",
  "Bissau",
  "Bissorã",
  "Bitam",
  "Bitlis",
  "Bitola",
  "Biên Hòa",
  "Bjelovar",
  "Blackrock",
  "Blagoevgrad",
  "Blantyre",
  "Blida",
  "Blitta",
  "Bloemfontein",
  "Bluefields",
  "Bo",
  "Boankra",
  "Bobo-Dioulasso",
  "Bobonong",
  "Boca Chica",
  "Bocaranga",
  "Bochum",
  "Bodrum",
  "Bodø",
  "Bog Walk",
  "Bogo",
  "Bogor",
  "Bogotá",
  "Bogra",
  "Bogué",
  "Bohicon",
  "Bokhtar",
  "Boksburg",
  "Boké",
  "Bolama",
  "Bologna",
  "Bolu",
  "Bolvadin",
  "Bonao",
  "Bongor",
  "Bonn",
  "Boosaaso",
  "Bopolu",
  "Bor",
  "Bor",
  "Bordeaux",
  "Bordj Bou Arreridj",
  "Borgarnes",
  "Borgo Maggiore",
  "Borj Hammoud",
  "Borj el Qoblé",
  "Borjomi",
  "Bornova",
  "Borvāyeh-ye Al Bū ‘Azīz",
  "Borås",
  "Borçka",
  "Bossangoa",
  "Bostaniçi",
  "Boston",
  "Bouaké",
  "Bouansa",
  "Bouar",
  "Bougouni",
  "Boutilimit",
  "Boyabat",
  "Bozdoğan",
  "Bozkurt",
  "Bozkır",
  "Bozoum",
  "Bozova",
  "Bozyazı",
  "Bozüyük",
  "Boğazlıyan",
  "Brades",
  "Braga",
  "Brampton",
  "Brasília",
  "Bratislava",
  "Brazzaville",
  "Braşov",
  "Breda",
  "Bregenz",
  "Bremen",
  "Brescia",
  "Brest",
  "Bria",
  "Bridgetown",
  "Brikama",
  "Brikama Ba",
  "Brisbane",
  "Bristol",
  "Brno",
  "Brokopondo",
  "Brooklyn",
  "Brownsweg",
  "Bruges",
  "Brussels",
  "Brāhmanbāria",
  "Brăila",
  "Buala",
  "Buba",
  "Bubanza",
  "Buca",
  "Bucak",
  "Bucaramanga",
  "Buchanan",
  "Bucharest",
  "Bucheon",
  "Budapest",
  "Budva",
  "Buea",
  "Buenaventura",
  "Buenos Aires",
  "Bugarama",
  "Buharkent",
  "Bujumbura",
  "Bukavu",
  "Bukhara",
  "Bukoba",
  "Bulancak",
  "Bulanık",
  "Bulawayo",
  "Buldan",
  "Bulolo",
  "Bumpe",
  "Bunia",
  "Buraydah",
  "Burco",
  "Burdur",
  "Burgas",
  "Burhaniye",
  "Bursa",
  "Bururi",
  "Busan",
  "Busumbala",
  "Butwāl",
  "Buurhakaba",
  "Buzău",
  "Buçimas",
  "Buôn Ma Thuột",
  "Buğdaylı",
  "Buḍhānilkanṭha",
  "Bu’aale",
  "Bwana Mkubwa",
  "Bydgoszcz",
  "Byumba",
  "Bávaro",
  "Béchar",
  "Béja",
  "Békéscsaba",
  "Béni Mellal",
  "Bünyan",
  "Büyük Çakırman",
  "Büyükorhan",
  "Büyükçekmece",
  "Bājil",
  "Bāmyān",
  "Bălţi",
  "Bēylul",
  "Bắc Ninh",
  "Cabimas",
  "Cabinda",
  "Cacheu",
  "Cacuaco",
  "Cadaado",
  "Caerdydd",
  "Cagayan de Oro",
  "Caguas",
  "Cahul",
  "Cairns",
  "Cairo",
  "Caió",
  "Cajamarca",
  "Calatrava",
  "Calgary",
  "Calheta de São Miguel",
  "Cali",
  "Callao",
  "Calliaqua",
  "Caloocan City",
  "Camagüey",
  "Campinas",
  "Campo Grande",
  "Canagatan",
  "Canberra",
  "Cancún",
  "Candelaria",
  "Canillo",
  "Cankuzo",
  "Cap-Haïtien",
  "Cape Coast",
  "Cape Town",
  "Capellen",
  "Capiatá",
  "Capitol Hill",
  "Caracas",
  "Carlos Manuel de Céspedes",
  "Carlow",
  "Carnot",
  "Carolina",
  "Carrefour",
  "Cartagena",
  "Casablanca",
  "Cascais",
  "Castries",
  "Catacamas",
  "Catania",
  "Cataño",
  "Catia La Mar",
  "Cativá",
  "Catió",
  "Cayenne",
  "Cayey",
  "Cazenga",
  "Cazin",
  "Ceadîr-Lunga",
  "Cebu City",
  "Ceel Baraf",
  "Celje",
  "Central Coast",
  "Central District",
  "Centre de Flacq",
  "Centro Habana",
  "Centurion",
  "Cetinje",
  "Ceyhan",
  "Ceylanpınar",
  "Chaguanas",
  "Chak Forty-one",
  "Chalchuapa",
  "Chalándri",
  "Champasak",
  "Changhua",
  "Changuinola",
  "Changwon",
  "Charentsavan",
  "Charleroi",
  "Charlotte Amalie",
  "Chattogram",
  "Chauddagram",
  "Chbar Mon",
  "Chegutu",
  "Chelyabinsk",
  "Chengdu",
  "Chennai",
  "Cheongju",
  "Chernihiv",
  "Cheung Chau",
  "Chiang Mai",
  "Chiatura",
  "Chiayi",
  "Chiba",
  "Chicago",
  "Chichicastenango",
  "Chiclayo",
  "Chiesanuova",
  "Chihuahua",
  "Chilibre",
  "Chililabombwe",
  "Chimbote",
  "Chimoio",
  "Chimteppa",
  "Chinandega",
  "Chinautla",
  "Chingola",
  "Chinhoyi",
  "Chiniot",
  "Chipata",
  "Chirchiq",
  "Chiredzi",
  "Chiromo",
  "Chirongui",
  "Chisinau",
  "Chitré",
  "Chitungwiza",
  "Chmistâr",
  "Choi Hung",
  "Choloma",
  "Chon Buri",
  "Chongqing",
  "Choybalsan",
  "Christchurch",
  "Chur",
  "Chèddra",
  "Chārīkār",
  "Chŏngju",
  "Ch’ŏnan",
  "Ch’ŏngjin",
  "Cibitoke",
  "Cidade Velha",
  "Cidade de Nacala",
  "Cide",
  "Ciego de Ávila",
  "Cienfuegos",
  "Cihanbeyli",
  "Cilacap",
  "City of Parañaque",
  "Ciudad Bolívar",
  "Ciudad Choluteca",
  "Ciudad Guayana",
  "Ciudad Nezahualcóyotl",
  "Ciudad Sandino",
  "Ciudad de la Costa",
  "Ciudad del Este",
  "Ciudad del Plata",
  "Cizre",
  "Claxton Bay",
  "Clervaux",
  "Clondalkin",
  "Cluj-Napoca",
  "Coatepeque",
  "Cobán",
  "Cochabamba",
  "Cocody",
  "Codru",
  "Coimbra",
  "Colcapirhua",
  "Cologne",
  "Colombo",
  "Colonia",
  "Colonia del Sacramento",
  "Colón",
  "Colón",
  "Comayagua",
  "Comayagüela",
  "Comilla",
  "Comodoro Rivadavia",
  "Comrat",
  "Conakry",
  "Concepción",
  "Constantine",
  "Constanţa",
  "Copenhagen",
  "Coquimbo",
  "Cork",
  "Corozal",
  "Corrientes",
  "Cosenza",
  "Coto Brus",
  "Cotonou",
  "Cottica",
  "Couva",
  "Coventry",
  "Craiova",
  "Cranbourne",
  "Croix-des-Bouquets",
  "Cuamba",
  "Cubal",
  "Cuenca",
  "Cuito",
  "Cumaná",
  "Cumayeri",
  "Curepipe",
  "Curitiba",
  "Cuscatancingo",
  "Cusco",
  "Cyangugu",
  "Cyuve",
  "Częstochowa",
  "Córdoba",
  "Córdoba",
  "Cúcuta",
  "Căuşeni",
  "Cēsis",
  "Cần Thơ",
  "Dabaga",
  "Dabola",
  "Daegu",
  "Daejeon",
  "Daga",
  "Dahūk",
  "Dakar",
  "Dalaman",
  "Dalanzadgad",
  "Dallas",
  "Daloa",
  "Damascus",
  "Dangriga",
  "Danilovgrad",
  "Danlí",
  "Dapaong",
  "Dar Naim",
  "Dar es Salaam",
  "Darende",
  "Dargeçit",
  "Darhan",
  "Darhan",
  "Darnah",
  "Daru",
  "Darwin",
  "Dar‘ā",
  "Dasmariñas",
  "Datça",
  "Daugavpils",
  "Daule",
  "Davao",
  "David",
  "Davutlar",
  "Dayr Abū Sa‘īd",
  "Dayr al Balaḩ",
  "Dayr az Zawr",
  "Dayrūţ",
  "Daşoguz",
  "Dbarwa",
  "Debar",
  "Debre Birhan",
  "Debre Mark’os",
  "Debrecen",
  "Dedza",
  "Dek’emhāre",
  "Delgado",
  "Delhi",
  "Delmas",
  "Delčevo",
  "Dembeni",
  "Demirci",
  "Demiryol",
  "Demirözü",
  "Demre",
  "Denizciler",
  "Denizli",
  "Denver",
  "Depok",
  "Derecik",
  "Dereli",
  "Derik",
  "Derince",
  "Derinkuyu",
  "Dessalines",
  "Desē",
  "Detroit",
  "Deurne",
  "Develi",
  "Devrek",
  "Dhaka",
  "Dhamār",
  "Dhangaḍhi̇̄",
  "Dharān",
  "Dhihdhoo",
  "Diabugu",
  "Dicle",
  "Didim",
  "Diego Martin",
  "Diekirch",
  "Diffa",
  "Differdange",
  "Digor",
  "Dijon",
  "Dikhil",
  "Dikili",
  "Dili",
  "Dilovası",
  "Diourbel",
  "Dire Dawa",
  "Diriamba",
  "Divo",
  "Divriği",
  "Diyadin",
  "Diyarbakır",
  "Djakotomé",
  "Djambala",
  "Djelfa",
  "Djibloho",
  "Djibo",
  "Djibouti",
  "Djougou",
  "Dnipro",
  "Doba",
  "Doboj",
  "Dobrich",
  "Doha",
  "Dolisie",
  "Domaa-Ahenkro",
  "Domagnano",
  "Domaniç",
  "Domoni",
  "Dondo",
  "Donetsk",
  "Dongguan",
  "Dori",
  "Dornbirn",
  "Dortmund",
  "Dosso",
  "Douala",
  "Douglas",
  "Douglas",
  "Douliu",
  "Doğanhisar",
  "Doğanşehir",
  "Doğubayazıt",
  "Dragash",
  "Drammen",
  "Dračevo",
  "Dresden",
  "Drochia",
  "Drogheda",
  "Dubai",
  "Dublin",
  "Dubrovnik",
  "Dubăsari",
  "Dudelange",
  "Duekoué",
  "Duisburg",
  "Dumbéa",
  "Dunedin",
  "Dunleary",
  "Durazno",
  "Durağan",
  "Durban",
  "Durleşti",
  "Durrës",
  "Dursunbey",
  "Dushanbe",
  "Dzolokpuita",
  "Dzüünharaa",
  "Dáli",
  "Dédougou",
  "Déressia",
  "Dörtyol",
  "Döşemealtı",
  "Dún Dealgan",
  "Düsseldorf",
  "Düzce",
  "Düziçi",
  "Düzköy",
  "Dārayyā",
  "Dīla",
  "Dūmā",
  "East London",
  "Ebebiyín",
  "Ecatepec",
  "Eceabat",
  "Echternach",
  "Ed Daein",
  "Ed Damazin",
  "Edd",
  "Edinburgh",
  "Edinburgh of the Seven Seas",
  "Edineţ",
  "Edirne",
  "Edmonton",
  "Edremit",
  "Edremit",
  "Eger",
  "Egilsstaðir",
  "Eindhoven",
  "Eiði",
  "Ejmiatsin",
  "Ekibastuz",
  "Ekinözü",
  "El Alto",
  "El Dorado",
  "El Fasher",
  "El Geneina",
  "El Ghâzîyé",
  "El Jadid",
  "El Khroub",
  "El Minié",
  "El Obeid",
  "El Progreso",
  "El Viejo",
  "Elazığ",
  "Elbasan",
  "Elbistan",
  "Elche",
  "Eldoret",
  "Eleşkirt",
  "Elmadağ",
  "Elmalı",
  "Eloy Alfaro",
  "Emet",
  "Emirdağ",
  "Emirgazi",
  "Encamp",
  "Encarnación",
  "Ennis",
  "Enschede",
  "Entebbe",
  "Erbaa",
  "Erbil",
  "Erciş",
  "Erdek",
  "Erdemli",
  "Erdenet",
  "Erenler",
  "Ereğli",
  "Ereğli",
  "Erfelek",
  "Ergani",
  "Erköklü",
  "Ermenek",
  "Eruh",
  "Erzin",
  "Erzincan",
  "Erzurum",
  "Esbjerg",
  "Escaldes-Engordany",
  "Esch-sur-Alzette",
  "Eschen",
  "Escuintla",
  "Esenler",
  "Esenyurt",
  "Eskilstuna",
  "Eskişehir",
  "Esmeraldas",
  "Espargos",
  "Espiye",
  "Espoo",
  "Essau",
  "Essen",
  "Estelí",
  "Eséka",
  "Etimesgut",
  "Evinayong",
  "Evren",
  "Ewarton",
  "Eydhafushi",
  "Eynesil",
  "Ezine",
  "Eğil",
  "Eğirdir",
  "Eşfahān",
  "Eşme",
  "Fada Ngourma",
  "Faetano",
  "Faisalabad",
  "Fajardo",
  "Falmouth",
  "Famagusta",
  "Famalicão",
  "Farafenni",
  "Farajok",
  "Faranah",
  "Farg‘ona",
  "Farim",
  "Farāh",
  "Fatsa",
  "Faya",
  "Feke",
  "Felidhoo",
  "Ferizaj",
  "Ferizli",
  "Ferkessédougou",
  "Fernando de la Mora",
  "Fethiye",
  "Fgura",
  "Fianarantsoa",
  "Fianga",
  "Fier",
  "Finglas",
  "Finike",
  "Fiorentino",
  "Fish Town",
  "Florence",
  "Florida",
  "Flying Fish Cove",
  "Foammulah",
  "Fomboni",
  "Fonadhoo",
  "Fort Wellington",
  "Fort-de-France",
  "Fortaleza",
  "Foshan",
  "Foumban",
  "Foya Tangia",
  "Foça",
  "Franceville",
  "Francistown",
  "Frankfurt",
  "Fredericia",
  "Fredrikstad",
  "Freeport City",
  "Freetown",
  "Fria",
  "Fribourg",
  "Frýdek-Místek",
  "Fuglafjørður",
  "Fukuoka",
  "Fulacunda",
  "Funadhoo",
  "Funafuti",
  "Fushë Kosovë",
  "Fushë-Krujë",
  "Fyzabad",
  "Fámjin",
  "Fès",
  "Fındıklı",
  "Gaalkacyo",
  "Gabela",
  "Gaborone",
  "Gabès",
  "Gabú",
  "Gafsa",
  "Gagnoa",
  "Gahini",
  "Galaţi",
  "Galle",
  "Gallipoli",
  "Galway",
  "Gambissara",
  "Gamboma",
  "Gamprin",
  "Ganta",
  "Ganzhou",
  "Gaoua",
  "Gaoua",
  "Garango",
  "Gargždai",
  "Garissa",
  "Garoowe",
  "Garoua",
  "Garðabær",
  "Gasa",
  "Gasparillo",
  "Gatumba",
  "Gatunda",
  "Gavarr",
  "Gaya",
  "Gaza",
  "Gaziantep",
  "Gaziemir",
  "Gazipaşa",
  "Gbarnga",
  "Gdańsk",
  "Gdynia",
  "Gebze",
  "Gedaref",
  "Gediz",
  "Geelong",
  "Geita",
  "Gemerek",
  "Gemlik",
  "General Santos",
  "Geneva",
  "Genoa",
  "Gent",
  "Genç",
  "George Town",
  "George Town",
  "Georgetown",
  "Georgetown",
  "Gerede",
  "Germasógeia",
  "Germencik",
  "Germiston",
  "Gerze",
  "Gevaş",
  "Geylegphug",
  "Geyve",
  "Ghanzi",
  "Gharyān",
  "Ghaznī",
  "Ghinda’e",
  "Ghorāhī",
  "Ghāziābād",
  "Ghŭlakandoz",
  "Gibraltar",
  "Gijón",
  "Giresun",
  "Gisborne",
  "Gisenyi",
  "Gitarama",
  "Gitega",
  "Gitega",
  "Giza",
  "Gizo",
  "Gjakovë",
  "Gjilan",
  "Gjirokastër",
  "Glasgow",
  "Gleno",
  "Gliwice",
  "Gllogovc",
  "Glyfáda",
  "Gobabis",
  "Godhavn",
  "Godomè",
  "Godāwari̇̄",
  "Godē",
  "Gogrial",
  "Goiânia",
  "Gold Coast",
  "Golubovci",
  "Goma",
  "Gonaïves",
  "Gondomar",
  "Goodlands",
  "Gori",
  "Goris",
  "Goroka",
  "Gostivar",
  "Gothenburg",
  "Goyang",
  "Goz-Beida",
  "Gqeberha",
  "Gradiška",
  "Granada",
  "Granada",
  "Grand Baie",
  "Grand Turk",
  "Graz",
  "Gračanica",
  "Greenville",
  "Grenoble",
  "Grevenmacher",
  "Groningen",
  "Groningen",
  "Grootfontein",
  "Gros Islet",
  "Grytviken",
  "Guadalajara",
  "Guadalupe",
  "Guangzhou",
  "Guantánamo",
  "Guarulhos",
  "Guatemala City",
  "Guayama",
  "Guayaquil",
  "Guaynabo",
  "Guidan Roumdji",
  "Guimarães",
  "Gujranwala",
  "Gulu",
  "Gumdag",
  "Gunjur",
  "Gurabo al Medio",
  "Gustavia",
  "Guácimo",
  "Guéckédou",
  "Guédiawaye",
  "Guérou",
  "Gwangju",
  "Gwelej",
  "Gweru",
  "Gyumri",
  "Gyzylgaya",
  "Győr",
  "Gävle",
  "Gödöllő",
  "Göksun",
  "Gökçe",
  "Gökçeada",
  "Gökçebey",
  "Gölbaşı",
  "Gölbaşı",
  "Gölcük",
  "Göle",
  "Gölhisar",
  "Gölköy",
  "Gölmarmara",
  "Gölpazarı",
  "Gölyaka",
  "Gömeç",
  "Gönen",
  "Gördes",
  "Görele",
  "Görükle",
  "Göynücek",
  "Gülağaç",
  "Gülnar",
  "Gülşehir",
  "Gümüşhacıköy",
  "Gümüşhane",
  "Gümüşova",
  "Güney",
  "Güneysu",
  "Güneysınır",
  "Güngören",
  "Gürgenpınarı",
  "Gürgentepe",
  "Güroymak",
  "Gürpınar",
  "Gürsu",
  "Gürün",
  "Güzelbahçe",
  "Güçlükonak",
  "Gāzipura",
  "Gəncə",
  "Haa",
  "Haapsalu",
  "Haarlem",
  "Habaswein",
  "Hacılar",
  "Hadera",
  "Hadim",
  "Haeju",
  "Hafnarfjörður",
  "Hagåtña",
  "Haifa",
  "Haiphong",
  "Hakkari",
  "Half Way Tree",
  "Halfeti",
  "Halifax",
  "Halmstad",
  "Hamadān",
  "Hamamatsu",
  "Hamburg",
  "Hamhŭng",
  "Hamidiye",
  "Hamilton",
  "Hamilton",
  "Hamilton",
  "Hammamet",
  "Hangzhou",
  "Hani",
  "Hannover",
  "Hanoi",
  "Hanımçiftliği",
  "Harare",
  "Harbel",
  "Harbiye",
  "Hargeysa",
  "Harper",
  "Harran",
  "Haskovo",
  "Hasköy",
  "Hassa",
  "Hasselt",
  "Hat Yai",
  "Hatay",
  "Haugesund",
  "Havana",
  "Havran",
  "Havsa",
  "Havza",
  "Havířov",
  "Haymana",
  "Hayrabolu",
  "Hazar",
  "Hazro",
  "Hebron",
  "Helsingborg",
  "Helsingør",
  "Helsinki",
  "Hendek",
  "Herceg Novi",
  "Herning",
  "Herāt",
  "Herẕliyya",
  "Heze",
  "Heṭauḍā",
  "Higüey",
  "Hikkaduwa",
  "Hilvan",
  "Hinche",
  "Hinda",
  "Hinthada",
  "Hiroshima",
  "Hisarcık",
  "Hithadhoo",
  "Hizan",
  "Hlatikulu",
  "Ho",
  "Ho Chi Minh City",
  "Hobart",
  "Hoima",
  "Holguín",
  "Holon",
  "Holstebro",
  "Homs",
  "Homyel’",
  "Honaz",
  "Hong Kong",
  "Honiara",
  "Hopa",
  "Horad Barysaw",
  "Horad Zhodzina",
  "Horasan",
  "Horqueta",
  "Horsens",
  "Hosa’ina",
  "Houndé",
  "Houston",
  "Hov",
  "Hovd",
  "Hpa-An",
  "Hradec Králové",
  "Hrazdan",
  "Hrodna",
  "Hsinchu",
  "Huacho",
  "Huambo",
  "Huancayo",
  "Huehuetenango",
  "Humacao",
  "Humenné",
  "Huánuco",
  "Huế",
  "Hvalba",
  "Hvannasund",
  "Hwange",
  "Hwasu-dong",
  "Hyderabad City",
  "Hyderābād",
  "Hyesan",
  "Hämeenlinna",
  "Höfn",
  "Hövsan",
  "Hørsholm",
  "Hüyük",
  "Hıdırbey",
  "Hınıs",
  "Hải Dương",
  "Ialoveni",
  "Iaşi",
  "Ibadan",
  "Ibagué",
  "Ibarra",
  "Ibb",
  "Ibb",
  "Ica",
  "Idhnā",
  "Idlib",
  "Ifakara",
  "Igreja",
  "Ijevan",
  "Ikare",
  "Ikeja",
  "Ikoto",
  "Ilgın",
  "Ilidža",
  "Ilioúpoli",
  "Ilopango",
  "Ilorin",
  "Ilulissat",
  "Ilıcaköy",
  "Imerintsiatosika",
  "Impfondo",
  "Incheon",
  "Indore",
  "Innsbruck",
  "Invercargill",
  "Iormughanlo",
  "Ipoh",
  "Ipswich",
  "Iquique",
  "Iquitos",
  "Iracoubo",
  "Iradan",
  "Irbid",
  "Iriba",
  "Iringa",
  "Irákleio",
  "Isale",
  "Isangel",
  "Isfana",
  "Isfara",
  "Isfisor",
  "Islamabad",
  "Isparta",
  "Istanbul",
  "Istaravshan",
  "Istog",
  "Itauguá",
  "Ituni",
  "Itá",
  "Izalco",
  "Izkī",
  "Izola",
  "Iğdır",
  "Jabālyā",
  "Jacmel",
  "Jaffna",
  "Jaipur",
  "Jakar",
  "Jakarta",
  "Jalal-Abad",
  "Jalapa",
  "Jalapa",
  "Jalālābād",
  "Jamaame",
  "Jamestown",
  "Janakpur",
  "Janjanbureh",
  "Janzūr",
  "Janīn",
  "Jaramānā",
  "Jarash",
  "Jbaïl",
  "Jean-Rabel",
  "Jeddah",
  "Jelgava",
  "Jericho",
  "Jerusalem",
  "Jesenice",
  "Jidd Ḩafş",
  "Jihlava",
  "Jijiga",
  "Jilib",
  "Jinja",
  "Jinotega",
  "Jitpur",
  "Jizzax",
  "Joal-Fadiout",
  "Joensuu",
  "Johannesburg",
  "Johor Bahru",
  "Jonava",
  "João Teves",
  "Joünié",
  "Juana Díaz",
  "Juba",
  "Juigalpa",
  "Juliaca",
  "Jutiapa",
  "Juticalpa",
  "Juárez",
  "Jwaneng",
  "Jyväskylä",
  "Jõgeva",
  "Jõhvi",
  "Jönköping",
  "Jēkabpils",
  "Jūrmala",
  "Kabala",
  "Kabarore",
  "Kabataş",
  "Kabinda",
  "Kabuga",
  "Kabul",
  "Kabwe",
  "Kadiolo",
  "Kadirli",
  "Kadoma",
  "Kadriye",
  "Kadıköy",
  "Kadınhanı",
  "Kaech’ŏn",
  "Kaesŏng",
  "Kaffrine",
  "Kafue",
  "Kaga Bandoro",
  "Kahama",
  "Kahramanmaraş",
  "Kailahun",
  "Kairouan",
  "Kajo Kaji",
  "Kaka",
  "Kakata",
  "Kalalé",
  "Kalamariá",
  "Kalbā",
  "Kale",
  "Kalecik",
  "Kallithéa",
  "Kalmunai",
  "Kalpitiya",
  "Kaman",
  "Kambia",
  "Kamenicë",
  "Kamnik",
  "Kampala",
  "Kampong Cham",
  "Kampong Chhnang",
  "Kampong Trach",
  "Kampong Tunah Jambu",
  "Kampot",
  "Kamsar",
  "Kamëz",
  "Kananga",
  "Kandahār",
  "Kandi",
  "Kandy",
  "Kandıra",
  "Kangal",
  "Kangersuatsiaq",
  "Kanggye",
  "Kanifing",
  "Kankan",
  "Kano",
  "Kanpur",
  "Kant",
  "Kanye",
  "Kaohsiung",
  "Kaolack",
  "Kapaklı",
  "Kapan",
  "Kaposvár",
  "Kara",
  "Kara-Balta",
  "Karaağaç",
  "Karaburun",
  "Karabük",
  "Karacabey",
  "Karacasu",
  "Karachi",
  "Karahallı",
  "Karaisalı",
  "Karaj",
  "Karakol",
  "Karakoçan",
  "Karaköprü",
  "Karaman",
  "Karamürsel",
  "Karapürçek",
  "Karapınar",
  "Karasu",
  "Karataş",
  "Karatepe",
  "Karayazı",
  "Karayılan",
  "Karaçoban",
  "Karbalā’",
  "Kargıpınar",
  "Karkamış",
  "Karlovac",
  "Karlovy Vary",
  "Karlskrona",
  "Karlıova",
  "Karonga",
  "Karpuzlu",
  "Karrānah",
  "Kars",
  "Kartal",
  "Karuzi",
  "Karviná",
  "Karşıyaka",
  "Kasama",
  "Kasangati",
  "Kasempa",
  "Kasese",
  "Kashikishi",
  "Kaspi",
  "Kassala",
  "Kasserine",
  "Kastamonu",
  "Kasulu",
  "Kasungu",
  "Katako-Kombe",
  "Kathmandu",
  "Kati",
  "Katima Mulilo",
  "Katlehong",
  "Katowice",
  "Kaunas",
  "Kavajë",
  "Kavak",
  "Kavaklıdere",
  "Kavieng",
  "Kawasaki",
  "Kaya",
  "Kayanza",
  "Kayapınar",
  "Kayes",
  "Kayes",
  "Kaynarca",
  "Kaynaşlı",
  "Kayseri",
  "Kazan",
  "Kazanlak",
  "Kaédi",
  "Kağızman",
  "Kaş",
  "Kaštel Stari",
  "Kebili",
  "Kecskemét",
  "Keelung",
  "Keetmanshoop",
  "Kefar Sava",
  "Keflavík",
  "Keila",
  "Keles",
  "Kelkit",
  "Kelo",
  "Kemalpaşa",
  "Kenema",
  "Kenitra",
  "Kennedy Town",
  "Kepsut",
  "Keratsíni",
  "Keren",
  "Kerewan",
  "Kermān",
  "Kermānshāh",
  "Kesbewa",
  "Keskin",
  "Kestel",
  "Keçiören",
  "Keşan",
  "Keşap",
  "Kharkiv",
  "Khartoum",
  "Khartoum North",
  "Khashuri",
  "Khawr Fakkān",
  "Khayelitsha",
  "Kherson",
  "Khmelnytskyi",
  "Khon Kaen",
  "Khowrhesht",
  "Khulna",
  "Khénifra",
  "Khān Yūnis",
  "Khōst",
  "Khŭjand",
  "Kiambu",
  "Kibaha",
  "Kibanseke Première",
  "Kibeho",
  "Kielce",
  "Kiffa",
  "Kigali",
  "Kikuyu",
  "Kikwit",
  "Kilifi",
  "Kilimli",
  "Kilinochchi",
  "Kilis",
  "Kimbe",
  "Kimberley",
  "Kimhae",
  "Kindia",
  "King Edward Point",
  "Kingston",
  "Kingston",
  "Kingston upon Hull",
  "Kingstown",
  "Kinshasa",
  "Kintampo",
  "Kirakira",
  "Kiraz",
  "Kireka",
  "Kirkja",
  "Kirkuk",
  "Kirundo",
  "Kisangani",
  "Kisenzi",
  "Kisii",
  "Kismaayo",
  "Kissidougou",
  "Kisumu",
  "Kitakyūshū",
  "Kitchener",
  "Kitenkela",
  "Kitwe",
  "Kladno",
  "Klagenfurt",
  "Klaipėda",
  "Klaksvík",
  "Klang",
  "Klinë",
  "Klosterneuburg",
  "Kluang",
  "Kobuleti",
  "Kocaali",
  "Kocaeli",
  "Kocaköy",
  "Kocasinan",
  "Koewarasan",
  "Koforidua",
  "Kogon Shahri",
  "Koh Kong",
  "Kohtla-Järve",
  "Koidu",
  "Koidu-Bulma",
  "Kokopo",
  "Kolašin",
  "Kolda",
  "Kolding",
  "Kolkāta",
  "Kollo",
  "Kolondiéba",
  "Kolonia",
  "Kolwezi",
  "Komárno",
  "Konak",
  "Konaklı",
  "Kongoussi",
  "Konibodom",
  "Konya",
  "Koné",
  "Koper",
  "Koprivnica",
  "Korgan",
  "Korhogo",
  "Korkut",
  "Korkuteli",
  "Koro",
  "Koror",
  "Kortrijk",
  "Korçë",
  "Kota Bharu",
  "Kota Kinabalu",
  "Kotka",
  "Kotla Qasim Khan",
  "Kotmale",
  "Kotor",
  "Koudougou",
  "Koulamoutou",
  "Koumantou",
  "Koumassi",
  "Koumra",
  "Koungou",
  "Koupéla",
  "Kourani",
  "Kouri",
  "Kouribga",
  "Kourou",
  "Kouré",
  "Kousséri",
  "Koutiala",
  "Kouvola",
  "Kovancılar",
  "Kowloon",
  "Kowloon City",
  "Koytendag",
  "Koyulhisar",
  "Kozan",
  "Kozlu",
  "Kozluk",
  "Koçarlı",
  "Kočani",
  "Kočevje",
  "Košice",
  "Kpalimé",
  "Kragujevac",
  "Kraków",
  "Kralendijk",
  "Kraljevo",
  "Kranj",
  "Krasnodar",
  "Krasnoyarsk",
  "Kratie",
  "Kraulshavn",
  "Krems an der Donau",
  "Kretinga",
  "Kristiansand",
  "Kriva Palanka",
  "Krong Kep",
  "Kruševac",
  "Kryvyi Rih",
  "Ksar",
  "Kuacjok",
  "Kuala Belait",
  "Kuala Lumpur",
  "Kuala Terengganu",
  "Kuantan",
  "Kuching",
  "Kudahuvadhoo",
  "Kueneng",
  "Kukës",
  "Kula",
  "Kuldīga",
  "Kulhudhuffushi",
  "Kullorsuaq",
  "Kulp",
  "Kulu",
  "Kulusuk",
  "Kumanovo",
  "Kumasi",
  "Kumbo",
  "Kumlu",
  "Kumluca",
  "Kumru",
  "Kumçatı",
  "Kundiawa",
  "Kunduz",
  "Kuopio",
  "Kuressaare",
  "Kurmuk",
  "Kurtalan",
  "Kurşunlu",
  "Kusapín",
  "Kushtia",
  "Kusŏng",
  "Kutaisi",
  "Kuwait City",
  "Kuyucak",
  "Kuzuculu",
  "Kuşadası",
  "Kvívík",
  "Kwai Chung",
  "Kwekwe",
  "Kyaukse",
  "Kyiv",
  "Kyrenia",
  "Kyustendil",
  "Kyzyl-Kyya",
  "Kyōto",
  "Káto Polemídia",
  "Kâhta",
  "Kâğıthane",
  "Kärdla",
  "Kéniéran",
  "Kétou",
  "Kévé",
  "Kópavogur",
  "Kökshetaū",
  "Köneürgench",
  "Köniz",
  "Köprübaşı",
  "Köprüköy",
  "Körfez",
  "Köse",
  "Köyceğiz",
  "Köşk",
  "Køge",
  "Kütahya",
  "Küçük Dalyan",
  "Küçükkuyu",
  "Küçükçekmece",
  "Kėdainiai",
  "Kınık",
  "Kırkağaç",
  "Kırklareli",
  "Kırıkhan",
  "Kırıkkale",
  "Kırşehir",
  "Kızılcahamam",
  "Kızılcaşar",
  "Kızılpınar",
  "Kızıltepe",
  "Kōbe",
  "Kūstī",
  "Kŭlob",
  "K’ebrī Beyah",
  "K’ebrī Dehar",
  "La Ceiba",
  "La Chaux-de-Fonds",
  "La Chorrera",
  "La Florida",
  "La Libertad",
  "La Lima",
  "La Lisa",
  "La Louvière",
  "La Massana",
  "La Paz",
  "La Pintana",
  "La Romana",
  "La Serena",
  "La Vega",
  "Labasa",
  "Labé",
  "Lae",
  "Lagos",
  "Lahore",
  "Lahti",
  "Lahān",
  "Lakatoro",
  "Lalmatie",
  "Lam Tin",
  "Lambaréné",
  "Lami",
  "Lanús",
  "Lappeenranta",
  "Lapseki",
  "Laqţah",
  "Larkana",
  "Larnaca",
  "Las Condes",
  "Las Palmas",
  "Las Piedras",
  "Las Piñas City",
  "Las Tunas",
  "Lashkar Gāh",
  "Lata",
  "Latacunga",
  "Latakia",
  "Latsia",
  "Lausanne",
  "Lautoka",
  "Laval",
  "Laventille",
  "Lavumisa",
  "Lazarevac",
  "Laâyoune",
  "Laç",
  "Le Havre",
  "Le Hochet",
  "Leava",
  "Leeds",
  "Leer",
  "Leicester",
  "Leicester",
  "Leipzig",
  "Lelydorp",
  "Leoben",
  "Leonding",
  "Leribe",
  "Les Cayes",
  "Lethem",
  "Letlhakane",
  "Letpandan",
  "Leulumoega",
  "Levakant",
  "Levice",
  "Lezhë",
  "León",
  "León de los Aldama",
  "Liberec",
  "Liberia",
  "Libreville",
  "Lice",
  "Lichinga",
  "Lida",
  "Liepāja",
  "Likasi",
  "Lille",
  "Lilongwe",
  "Lima",
  "Limassol",
  "Limerick",
  "Limpio",
  "Linden",
  "Linköping",
  "Linstead",
  "Linyi",
  "Linz",
  "Lipjan",
  "Liquiçá",
  "Lira",
  "Lisbon",
  "Liverpool",
  "Liwonde",
  "Liège",
  "Ljubljana",
  "Lobamba",
  "Lobatse",
  "Lobito",
  "Lochau",
  "Logatec",
  "Loja",
  "Lomé",
  "London",
  "London",
  "Longyearbyen",
  "Los Alcarrizos",
  "Los Angeles",
  "Los Minas",
  "Los Teques",
  "Lospalos",
  "Louang Namtha",
  "Louangphabang",
  "Loudima Poste",
  "Louga",
  "Loures",
  "Loutété",
  "Lower Hutt",
  "Loznica",
  "Luanda",
  "Luanshya",
  "Luba",
  "Lubango",
  "Lublin",
  "Lubumbashi",
  "Lucan",
  "Lucaya",
  "Lucea",
  "Lucerne",
  "Lucknow",
  "Luena",
  "Lufilufi",
  "Lugano",
  "Luganville",
  "Lugazi",
  "Luhansk",
  "Lukavac",
  "Lunga-Lunga",
  "Lunsar",
  "Luque",
  "Lusaka",
  "Lushnjë",
  "Luuq",
  "Luxembourg",
  "Lviv",
  "Lyon",
  "Lárisa",
  "Léogâne",
  "Léré",
  "Lørenskog",
  "Lüderitz",
  "Lüleburgaz",
  "Lənkəran",
  "M.Ə. Rəsulzadə",
  "Maardu",
  "Maastricht",
  "Mabaruma",
  "Macau",
  "Maceió",
  "Macenta",
  "Machakos",
  "Machala",
  "Madang",
  "Madaoua",
  "Madina do Boé",
  "Madingou",
  "Madirovalo",
  "Madrid",
  "Madīnat Zāyid",
  "Madīnat ash Shamāl",
  "Madīnat Ḩamad",
  "Madīnat ‘Īsá",
  "Mafeteng",
  "Maga",
  "Magburaka",
  "Maghalleen",
  "Magway",
  "Magwe",
  "Mahajanga",
  "Mahalapye",
  "Maharagama",
  "Mahdia",
  "Mahibadhoo",
  "Mahilyow",
  "Mahmutlar",
  "Mahmutlu",
  "Maia",
  "Maiduguri",
  "Maina",
  "Maipú",
  "Majuro",
  "Makamba",
  "Makassar",
  "Makati City",
  "Makhachkala",
  "Makiivka",
  "Makokou",
  "Makoua",
  "Malabo",
  "Maladzyechna",
  "Malakal",
  "Malang",
  "Malanje",
  "Malanville",
  "Malatya",
  "Malazgirt",
  "Maldonado",
  "Male",
  "Malema",
  "Maliana",
  "Malindi",
  "Malkara",
  "Malmö",
  "Mamak",
  "Mambéré",
  "Mamou",
  "Mamoudzou",
  "Man",
  "Manadhoo",
  "Managua",
  "Manama",
  "Manatuto",
  "Manaus",
  "Manavgat",
  "Manchester",
  "Mandalay",
  "Mandeville",
  "Mandza",
  "Mangochi",
  "Manila",
  "Manisa",
  "Manizales",
  "Mansa",
  "Mansa Konko",
  "Manta",
  "Manukau City",
  "Manyas",
  "Manzanillo",
  "Manzini",
  "Mapoteng",
  "Maputo",
  "Maputsoe",
  "Mar del Plata",
  "Marabella",
  "Maracaibo",
  "Maradi",
  "Marcory",
  "Mardin",
  "Marg‘ilon",
  "Marianao",
  "Mariano Roque Alonso",
  "Maribor",
  "Maridi",
  "Mariental",
  "Marigot",
  "Marijampolė",
  "Mariupol",
  "Marka",
  "Markham",
  "Marmara Ereğlisi",
  "Marmaris",
  "Marneuli",
  "Marondera",
  "Maroua",
  "Maroúsi",
  "Marrakech",
  "Marsaskala",
  "Marseille",
  "Martin",
  "Mary",
  "Masaka",
  "Masallātah",
  "Masaya",
  "Maseru",
  "Mashhad",
  "Masindi",
  "Masis",
  "Masqaţ",
  "Massawa",
  "Masvingo",
  "Mata-Utu",
  "Matadi",
  "Matagalpa",
  "Matamey",
  "Matanzas",
  "Mateare",
  "Matina",
  "Matola",
  "Matosinhos",
  "Maturín",
  "Maun",
  "Maungdaw",
  "Mauren",
  "Mawanella",
  "Mawlamyine",
  "Maxixe",
  "May Pen",
  "Mayagüez",
  "Mayumba",
  "Mazabuka",
  "Mazenod",
  "Mazyr",
  "Mazār-e Sharīf",
  "Mazıdağı",
  "Maçka",
  "Maīmanah",
  "Maştağa",
  "Maţraḩ",
  "Mažeikiai",
  "Ma‘arrat an Nu‘mān",
  "Ma‘ān",
  "Mbabane",
  "Mbaké",
  "Mbale",
  "Mbandaka",
  "Mbarara",
  "Mbaïki",
  "Mbeya",
  "Mbini",
  "Mbuji-Mayi",
  "Mchinji",
  "Mecca",
  "Mechelen",
  "Mecitözü",
  "Medan",
  "Medellín",
  "Medenine",
  "Medina",
  "Medina Estates",
  "Meerzorg",
  "Mehtar Lām",
  "Meiktila",
  "Mejicanos",
  "Mekele",
  "Meknès",
  "Melaka",
  "Melbourne",
  "Melekeok",
  "Melikgazi",
  "Mellieħa",
  "Melo",
  "Mendefera",
  "Menderes",
  "Mendi",
  "Menemen",
  "Menongue",
  "Meram",
  "Mercedes",
  "Meriç",
  "Merlo",
  "Mersch",
  "Mersin",
  "Merzifon",
  "Messina",
  "Mesudiye",
  "Mexicali",
  "Mexico City",
  "Mezitli",
  "Miami",
  "Michalovce",
  "Micoud",
  "Midyat",
  "Mikkeli",
  "Milagro",
  "Milan",
  "Milas",
  "Minas",
  "Mindelo",
  "Mindouli",
  "Mingəçevir",
  "Minneapolis",
  "Minsk",
  "Mirzāpur",
  "Miskolc",
  "Mississauga",
  "Missérété",
  "Mitchells Plain",
  "Mitrovicë",
  "Mityana",
  "Mitzic",
  "Mixco",
  "Mişrātah",
  "Moanda",
  "Mochudi",
  "Mocuba",
  "Mocuba",
  "Modi‘in Makkabbim Re‘ut",
  "Moengo",
  "Mogadishu",
  "Mogoditshane",
  "Mohale’s Hoek",
  "Mohammedia",
  "Mojkovac",
  "Moka",
  "Molepolole",
  "Molo",
  "Mombasa",
  "Momostenango",
  "Monaco",
  "Monastir",
  "Mongar",
  "Mongo",
  "Mongomo",
  "Mongu",
  "Monrovia",
  "Mons",
  "Mont-Dore",
  "Montegiardino",
  "Montego Bay",
  "Montepuez",
  "Montero",
  "Monterrey",
  "Montería",
  "Montevideo",
  "Montpellier",
  "Montréal",
  "Monywa",
  "Moortebeek",
  "Mopti",
  "Mora",
  "Morant Bay",
  "Moratuwa",
  "Morelia",
  "Morogoro",
  "Moroni",
  "Moscow",
  "Mosopa",
  "Mossaka",
  "Mossendjo",
  "Most",
  "Mosta",
  "Mostar",
  "Mosul",
  "Motema",
  "Mouila",
  "Moundou",
  "Mount Hagen",
  "Mount Lavinia",
  "Mpanda",
  "Mponela",
  "Mporokoso",
  "Msaken",
  "Muang Sing",
  "Muar",
  "Mubende",
  "Mucur",
  "Mudanya",
  "Mufulira",
  "Muhanga",
  "Mukono",
  "Mulanje",
  "Muli",
  "Mulifanua",
  "Multan",
  "Mumbai",
  "Munich",
  "Muradiye",
  "Muramvya",
  "Muratlı",
  "Murcia",
  "Murska Sobota",
  "Muscat",
  "Mushin",
  "Mustafakemalpaşa",
  "Mut",
  "Mutare",
  "Mutki",
  "Mutsamudu",
  "Muyinga",
  "Muğla",
  "Muş",
  "Mu’tah",
  "Mwanza",
  "Mwanza",
  "Myawadi",
  "Myeik",
  "Myitkyina",
  "Mykolaiv",
  "Mymensingh",
  "Mzimba",
  "Mzuzu",
  "Málaga",
  "Mékambo",
  "Mérida",
  "Mérida",
  "Mésa Geitoniá",
  "Métouia",
  "Mörön",
  "Münster",
  "Mādabā",
  "Mārupe",
  "Nabatîyé",
  "Nadi",
  "Nagoya",
  "Naifaru",
  "Nairobi",
  "Nakasi",
  "Nakhon Ratchasima",
  "Nakhon Sawan",
  "Nakhon Si Thammarat",
  "Nako",
  "Nakuru",
  "Nalayh",
  "Nallıhan",
  "Nam Định",
  "Namangan",
  "Nampo",
  "Nampula",
  "Namur",
  "Nansana",
  "Nantes",
  "Nanyang",
  "Napier",
  "Naples",
  "Naranjo",
  "Narlıca",
  "Narlıdere",
  "Narman",
  "Narsarsuaq",
  "Narva",
  "Naryn",
  "Nassau",
  "Natal",
  "Natogyi",
  "Naucalpan de Juárez",
  "Nausori",
  "Navan",
  "Navapolatsk",
  "Navgilem",
  "Navoiy",
  "Naxxar",
  "Naxçıvan",
  "Nay Pyi Taw",
  "Nazareth",
  "Nazilli",
  "Nazrēt",
  "Nchelenge",
  "Ndendé",
  "Ndjili",
  "Ndola",
  "Ndora",
  "Nefasīt",
  "Negombo",
  "Negotino",
  "Neiafu",
  "Nek’emtē",
  "Nelson",
  "Nepālgañj",
  "Nerima",
  "Netanya",
  "Neves",
  "Nevşehir",
  "New Amsterdam",
  "New Kru Town",
  "New Plymouth",
  "New York",
  "Newcastle",
  "Newcastle",
  "Newton",
  "Nezahualcóyotl",
  "Ngaoundéré",
  "Ngerulmud",
  "Ngong",
  "Ngororero",
  "Ngozi",
  "Nguigmi",
  "Nha Trang",
  "Nhlangano",
  "Niamey",
  "Niamtougou",
  "Nice",
  "Nicosia",
  "Nicoya",
  "Nieuw Amsterdam",
  "Nieuw Nickerie",
  "Niigata",
  "Nijmegen",
  "Niksar",
  "Nikšić",
  "Nilandhoo",
  "Nilüfer",
  "Nimule",
  "Niono",
  "Nioro",
  "Nitra",
  "Nizhniy Novgorod",
  "Nizip",
  "Nizwá",
  "Niğde",
  "Niš",
  "Njeru",
  "Nkayi",
  "Nkhotakota",
  "Nkongsamba",
  "Nneyi-Umuleri",
  "Nola",
  "Nonthaburi",
  "Nordre Fåle",
  "Norrköping",
  "Northcote",
  "Norton",
  "Norðragøta",
  "Notsé",
  "Nottingham",
  "Nouadhibou",
  "Nouakchott",
  "Nouméa",
  "Nova Gorica",
  "Novi Pazar",
  "Novi Sad",
  "Novo Mesto",
  "Novopokrovka",
  "Novosibirsk",
  "Nové Zámky",
  "Nsanje",
  "Ntcheu",
  "Ntoum",
  "Nueva Guinea",
  "Nuevo Arraiján",
  "Nukus",
  "Nuku‘alofa",
  "Nurdağı",
  "Nuremberg",
  "Nurhak",
  "Nusaybin",
  "Nuuk",
  "Nu‘ayjah",
  "Nyakosoba",
  "Nyala",
  "Nyamata",
  "Nyanza",
  "Nyíregyháza",
  "Næstved",
  "Néa Smýrni",
  "Néma",
  "Níkaia",
  "Nîmes",
  "Nāblus",
  "Nāgpur",
  "Nālūt",
  "Nārāyanganj",
  "N’Djamena",
  "N’Zérékoré",
  "Obburdon",
  "Obock",
  "Obuase",
  "Ocho Rios",
  "Odense",
  "Odesa",
  "Odivelas",
  "Oeiras",
  "Of",
  "Ogbomoso",
  "Ogre",
  "Ohrid",
  "Okahandja",
  "Okondja",
  "Olaine",
  "Olanchito",
  "Old Harbour",
  "Olmaliq",
  "Olomouc",
  "Oltu",
  "Omatjete",
  "Omboué",
  "Omdurman",
  "Omsk",
  "Onchan",
  "Ondangwa",
  "Ondokuzmayıs",
  "Ongata Rongai",
  "Ongwediva",
  "Onitsha",
  "Onverwacht",
  "Opava",
  "Opuwo",
  "Oradea",
  "Oral",
  "Orange Walk",
  "Oranjestad",
  "Oranjestad",
  "Ordino",
  "Ordu",
  "Orhaneli",
  "Orhangazi",
  "Orhei",
  "Orsha",
  "Ortaca",
  "Ortakent",
  "Ortaklar",
  "Ortaköy",
  "Ortaköy",
  "Ortaköy",
  "Oruro",
  "Oruro",
  "Orūmīyeh",
  "Osh",
  "Oshakati",
  "Oshawa",
  "Oshikango",
  "Osijek",
  "Oslo",
  "Osmancık",
  "Osmaneli",
  "Osmangazi",
  "Osmaniye",
  "Ostend",
  "Ostrava",
  "Otjiwarongo",
  "Ottawa",
  "Ouagadougou",
  "Ouahigouya",
  "Ouangani",
  "Ouani",
  "Ouargla",
  "Oujda-Angad",
  "Oulu",
  "Oum Hadjer",
  "Oumé",
  "Ouésso",
  "Owando",
  "Owendo",
  "Owerri",
  "Oyem",
  "Oğuzeli",
  "Paamiut",
  "Pacora",
  "Padang",
  "Padova",
  "Paghmān",
  "Pago Pago",
  "Paide",
  "Pak Kret",
  "Pak Tin Pa",
  "Pakxan",
  "Pakxé",
  "Pala Oua",
  "Palanga",
  "Palapye",
  "Palembang",
  "Palermo",
  "Palermo",
  "Palikir",
  "Palma",
  "Palmares",
  "Palmerston North",
  "Palu",
  "Palé",
  "Pamukkale",
  "Pamukova",
  "Panama City",
  "Pando",
  "Panevėžys",
  "Panjakent",
  "Pantanal",
  "Pante Macassar",
  "Pančevo",
  "Paoskoto",
  "Paoua",
  "Paoy Paet",
  "Papeete",
  "Paphos",
  "Parakou",
  "Paralímni",
  "Paramaribo",
  "Paraná",
  "Pardubice",
  "Paris",
  "Parma",
  "Paro",
  "Pasig City",
  "Pasinler",
  "Pasir Gudang",
  "Pasto",
  "Pathein",
  "Patnos",
  "Pavlodar",
  "Paysandú",
  "Pazar",
  "Pazarcık",
  "Pazardzhik",
  "Pazaryeri",
  "Païta",
  "Pedra Badejo",
  "Pedro Juan Caballero",
  "Pejë",
  "Peka",
  "Pekanbaru",
  "Pelitli",
  "Pemagatshel",
  "Pemba",
  "Penal",
  "Pendembu",
  "Pendik",
  "Penonomé",
  "Pereira",
  "Peristéri",
  "Perm",
  "Pernik",
  "Perth",
  "Pervari",
  "Perşembe",
  "Peshawar",
  "Petaling Jaya",
  "Petapa",
  "Petare",
  "Petaẖ Tiqwa",
  "Petite Rivière de l’Artibonite",
  "Petnjica",
  "Petropavl",
  "Petržalka",
  "Peñalolén",
  "Phatthaya",
  "Philadelphia",
  "Philipsburg",
  "Phnom Penh",
  "Phoenix",
  "Phuntsholing",
  "Phôngsali",
  "Phônsavan",
  "Picos",
  "Pietermaritzburg",
  "Piggs Peak",
  "Pikine",
  "Pilar",
  "Pinar del Río",
  "Pindi Bhattian",
  "Pingtung",
  "Pingzhen",
  "Pinsk",
  "Piraeus",
  "Piraziz",
  "Pita",
  "Piteşti",
  "Pitseng",
  "Piura",
  "Plaine Magnien",
  "Planken",
  "Plav",
  "Pleven",
  "Pljevlja",
  "Ploieşti",
  "Plovdiv",
  "Plungė",
  "Plymouth",
  "Plzeň",
  "Podgorica",
  "Podujevë",
  "Pogradec",
  "Point Fortin",
  "Pointe-Noire",
  "Pointe-à-Pitre",
  "Pokhara",
  "Polatlı",
  "Polatsk",
  "Poltava",
  "Ponce",
  "Ponta do Sol",
  "Popondetta",
  "Poprad",
  "Pori",
  "Porirua",
  "Porkeri",
  "Port Antonio",
  "Port Harcourt",
  "Port Laoise",
  "Port Loko",
  "Port Louis",
  "Port Maria",
  "Port Morant",
  "Port Moresby",
  "Port Said",
  "Port Sudan",
  "Port of Spain",
  "Port-Bouët",
  "Port-Gentil",
  "Port-Vila",
  "Port-au-Prince",
  "Port-de-Paix",
  "Portmore",
  "Porto",
  "Porto Alegre",
  "Porto Inglês",
  "Porto Novo",
  "Porto-Novo",
  "Portoviejo",
  "Portsmouth",
  "Posadas",
  "Postojna",
  "Poti",
  "Potosí",
  "Pouytenga",
  "Považská Bystrica",
  "Pozantı",
  "Poznań",
  "Požarevac",
  "Prague",
  "Praia",
  "Prato",
  "Presidente Franco",
  "Pretoria",
  "Prey Veng",
  "Prešov",
  "Prievidza",
  "Prijedor",
  "Prilep",
  "Princes Town",
  "Princetown",
  "Pristina",
  "Prizren",
  "Probištip",
  "Ptuj",
  "Pucallpa",
  "Puebla",
  "Puente Alto",
  "Puerto Cortés",
  "Puerto La Cruz",
  "Puerto Limón",
  "Puerto Plata",
  "Puerto Villarroel",
  "Pujehun",
  "Pul-e Khumrī",
  "Pula",
  "Punakha",
  "Pune",
  "Punta Gorda",
  "Puntarenas",
  "Punto Fijo",
  "Pursat",
  "Pyongyang",
  "Pátra",
  "Pärnu",
  "Pèlèngana",
  "Pécs",
  "Pétion-Ville",
  "Põlva",
  "Pütürge",
  "Pīshbar",
  "Pınarbaşı",
  "P’yŏng-dong",
  "P’yŏngsŏng-si",
  "Qaanaaq",
  "Qabb Eliâs",
  "Qabr as Sitt",
  "Qabāţīyah",
  "Qalqīlyah",
  "Qaqortoq",
  "Qaraghandy",
  "Qaratog",
  "Qaraçuxur",
  "Qardho",
  "Qarshi",
  "Qasigiannguit",
  "Qiloane",
  "Qom",
  "Qormi",
  "Qostanay",
  "Qo‘qon",
  "Quanzhou",
  "Quartier Militaire",
  "Quatre Bornes",
  "Quebec City",
  "Queens",
  "Quelimane",
  "Quesada",
  "Quetta",
  "Quetzaltenango",
  "Quevedo",
  "Quezon City",
  "Quilicura",
  "Quillacollo",
  "Quilmes",
  "Quinhámel",
  "Quito",
  "Qurayyāt",
  "Quthing",
  "Quảng Hà",
  "Qyzylorda",
  "Rabat",
  "Rabat",
  "Radom",
  "Radès",
  "Rafaḩ",
  "Rahovec",
  "Rajin",
  "Rakvere",
  "Ramabitsa",
  "Ramallah",
  "Ramat Gan",
  "Ramotswa",
  "Ramu",
  "Rancagua",
  "Randburg",
  "Randers",
  "Rangapukur",
  "Rangoon",
  "Rangpur",
  "Rapla",
  "Rasdhoo",
  "Rasht",
  "Ratau",
  "Ratnapura",
  "Rawalpindi",
  "Ra’s al Khaymah",
  "Reading",
  "Rebola",
  "Rechytsa",
  "Recife",
  "Redange-sur-Attert",
  "Refahiye",
  "Rehoboth",
  "Reims",
  "Remich",
  "Renk",
  "Rennes",
  "Resistencia",
  "Reyhanlı",
  "Reykjavík",
  "Reşadiye",
  "Reẖovot",
  "Ribeira Brava",
  "Ribeira Grande",
  "Riberalta",
  "Richard-Toll",
  "Riga",
  "Rijeka",
  "Rio de Janeiro",
  "Riobamba",
  "Rishon LeẔiyyon",
  "Rivera",
  "Riyadh",
  "Rize",
  "Road Town",
  "Robertsport",
  "Roghun",
  "Rome",
  "Roodepoort",
  "Rosario",
  "Rose Belle",
  "Roseau",
  "Roskilde",
  "Rosso",
  "Rostov",
  "Rotorua",
  "Rotterdam",
  "Roura",
  "Rovaniemi",
  "Rožaje",
  "Rubengera",
  "Rufisque",
  "Ruggell",
  "Ruhengeri",
  "Rumbek",
  "Rumonge",
  "Rumphi",
  "Rundu",
  "Rusape",
  "Ruse",
  "Rustavi",
  "Rustenburg",
  "Rutana",
  "Ruyigi",
  "Rzeszów",
  "Râmnicu Vâlcea",
  "Rîbniţa",
  "Rājkot",
  "Rājshāhi",
  "Rēzekne",
  "Sabara Bangou",
  "Sacaba",
  "Saclepea",
  "Sada",
  "Safi",
  "Safotu",
  "Safotulafai",
  "Safranbolu",
  "Saimbeyli",
  "Saint Ann’s Bay",
  "Saint David’s",
  "Saint George’s",
  "Saint Helier",
  "Saint John’s",
  "Saint Joseph",
  "Saint Paul’s Bay",
  "Saint Peter Port",
  "Saint Petersburg",
  "Saint Sampson",
  "Saint-Benoît",
  "Saint-Denis",
  "Saint-Georges",
  "Saint-Laurent-du-Maroni",
  "Saint-Louis",
  "Saint-Marc",
  "Saint-Michel de l’Atalaye",
  "Saint-Pierre",
  "Saint-Étienne",
  "Saitama",
  "Sakai",
  "Sakarya",
  "Sakiet ed Daier",
  "Sakubva",
  "Sal Rei",
  "Salaspils",
  "Salavan",
  "Saldus",
  "Sale",
  "Saleaula",
  "Salihli",
  "Salihorsk",
  "Salima",
  "Salo",
  "Salta",
  "Saltangará",
  "Saltillo",
  "Salto",
  "Salvador",
  "Salzburg",
  "Samamea",
  "Samandağ",
  "Samara",
  "Samarkand",
  "Sambava",
  "Samdrup Jongkhar",
  "Same",
  "Samobor",
  "Samraong",
  "Samsun",
  "Samtredia",
  "Samtse",
  "Samā’il",
  "San Antonio",
  "San Bernardo",
  "San Carlos",
  "San Cristóbal",
  "San Cristóbal",
  "San Diego",
  "San Fernando",
  "San Francisco",
  "San Francisco de Macorís",
  "San Germán",
  "San Ignacio",
  "San Isidro",
  "San Jose del Monte",
  "San José",
  "San José",
  "San Juan",
  "San Juan",
  "San Juan",
  "San Juan",
  "San Juan Opico",
  "San Juan Sacatepéquez",
  "San Lorenzo",
  "San Luis",
  "San Marcos",
  "San Marino",
  "San Martín",
  "San Miguel",
  "San Miguel de Tucumán",
  "San Miguel del Padrón",
  "San Miguelito",
  "San Pedro",
  "San Pedro Carchá",
  "San Pedro Sula",
  "San Pedro de Macorís",
  "San Rafael",
  "San Ramón",
  "San Salvador",
  "San Salvador de Jujuy",
  "San Tung Chung Hang",
  "San Ġiljan",
  "San Ġwann",
  "San-Pédro",
  "Sanaa",
  "Sancti Spíritus",
  "Sandakan",
  "Sandavágur",
  "Sandefjord",
  "Sandnes",
  "Sandur",
  "Sandvika",
  "Sangereng",
  "Sangolquí",
  "Sangre Grande",
  "Sankt Gallen",
  "Sankt Pölten",
  "Sanniquellie",
  "Sannār",
  "Sansanné-Mango",
  "Sanski Most",
  "Sant Julià de Lòria",
  "Santa Ana",
  "Santa Clara",
  "Santa Cruz",
  "Santa Cruz",
  "Santa Cruz",
  "Santa Cruz de la Sierra",
  "Santa Fe",
  "Santa Lucía Cotzumalguapa",
  "Santa Marta",
  "Santa Rosa de Copán",
  "Santa Tecla",
  "Santa Teresa del Tuy",
  "Santana",
  "Santiago",
  "Santiago",
  "Santiago",
  "Santiago de Baney",
  "Santiago de Cuba",
  "Santiago del Estero",
  "Santo António",
  "Santo Domingo",
  "Santo Domingo",
  "Santo Domingo Este",
  "Santo Domingo de los Colorados",
  "Santos",
  "Sanwal",
  "Sapanca",
  "Sapporo",
  "Sarajevo",
  "Sarandë",
  "Sarapiquí",
  "Saratamata",
  "Saratov",
  "Saray",
  "Saray",
  "Saraykent",
  "Sarayköy",
  "Sarayönü",
  "Sareh Mowndeh",
  "Sargodha",
  "Sarh",
  "Sarikishty",
  "Sariwŏn",
  "Sarpang",
  "Sarpsborg",
  "Saruhanlı",
  "Sarıgöl",
  "Sarıkamış",
  "Sarıkaya",
  "Sarıoğlan",
  "Sarıveliler",
  "Sarıyer",
  "Sarız",
  "Sarıçam",
  "Sason",
  "Satu Mare",
  "Satupa‘itea",
  "Saurimo",
  "Sauðárkrókur",
  "Savanna-la-Mar",
  "Savannakhet",
  "Savar",
  "Savaştepe",
  "Savissivik",
  "Savur",
  "Sawrān",
  "Saynshand",
  "Say’ūn",
  "Saḩāb",
  "Scarborough",
  "Schaan",
  "Schaarbeek",
  "Schaffhausen",
  "Schellenberg",
  "Scoresbysund",
  "Seattle",
  "Seberang Jaya",
  "Seferhisar",
  "Segbwema",
  "Seinäjoki",
  "Seixal",
  "Sekondi",
  "Selendi",
  "Selfoss",
  "Selibe Phikwe",
  "Selim",
  "Selimpaşa",
  "Selçuk",
  "Selçuklu",
  "Semarang",
  "Semey",
  "Senaki",
  "Sendai",
  "Senekane",
  "Senirkent",
  "Seoul",
  "Serdar",
  "Serekunda",
  "Seremban",
  "Seria",
  "Serik",
  "Serinhisar",
  "Serinyol",
  "Serowe",
  "Serravalle",
  "Sesvete",
  "Setagaya",
  "Sevan",
  "Sevastopol",
  "Sevilla",
  "Sevilla de Niefang",
  "Seydişehir",
  "Seyhan",
  "Seyitgazi",
  "Sfax",
  "Sha Kok Mei",
  "Sha Tin",
  "Shagamu",
  "Shah Alam",
  "Shahrisabz",
  "Sham Shui Po",
  "Shanghai",
  "Sharjah",
  "Shashemenē",
  "Sheffield",
  "Shek Tong Tsui",
  "Shek Wai Kok",
  "Shekhupura",
  "Shenzhen",
  "Shibirghān",
  "Shibīn al Qanāţir",
  "Shināş",
  "Shkodër",
  "Shubrā al Khaymah",
  "Shumen",
  "Shymkent",
  "Shyorongi",
  "Shīrāz",
  "Si Racha",
  "Sialkot City",
  "Sibiti",
  "Sibiu",
  "Sibut",
  "Side",
  "Sidi Aïssa",
  "Sidi Bel Abbès",
  "Sidi Bouzid",
  "Sidon",
  "Siem Reap",
  "Sigatoka",
  "Siguatepeque",
  "Siguiri",
  "Sigulda",
  "Sihanoukville",
  "Siirt",
  "Sikasso",
  "Silifke",
  "Silivri",
  "Silkeborg",
  "Sillamäe",
  "Siloe",
  "Silopi",
  "Silvan",
  "Simav",
  "Simferopol",
  "Sinanpaşa",
  "Sincan",
  "Singa",
  "Singapore",
  "Singida",
  "Sinnamary",
  "Sinnūris",
  "Sinop",
  "Sint-Niklaas",
  "Sintra",
  "Sinŭiju",
  "Sion",
  "Sirka",
  "Sirājganj",
  "Sisak",
  "Sisimiut",
  "Sisophon",
  "Siteki",
  "Sitrah",
  "Siuna",
  "Sivas",
  "Sivaslı",
  "Siverek",
  "Sivrice",
  "Sivrihisar",
  "Skellefteå",
  "Skenderaj",
  "Skien",
  "Skikda",
  "Skopje",
  "Skopun",
  "Slavonski Brod",
  "Sliema",
  "Sliven",
  "Slobozia",
  "Slovenska Bistrica",
  "Smederevo",
  "Soacha",
  "Sodo",
  "Sofia",
  "Sokhumi",
  "Sokodé",
  "Sokuluk",
  "Sola",
  "Soledad",
  "Solhan",
  "Solwezi",
  "Soma",
  "Somasso",
  "Sonsonate",
  "Sopron",
  "Sorgun",
  "Soroca",
  "Sosnowiec",
  "Sotouboua",
  "Soubré",
  "Sousse",
  "Southampton",
  "Soweto",
  "Soyapango",
  "Spanish Town",
  "Spišská Nová Ves",
  "Split",
  "Sremska Mitrovica",
  "Sri Jayewardenepura Kotte",
  "Stanley",
  "Stara Pazova",
  "Stara Zagora",
  "Stavanger",
  "Stepanavan",
  "Steyr",
  "Stockholm",
  "Stoke-on-Trent",
  "Strasbourg",
  "Straşeni",
  "Struga",
  "Strumica",
  "Stuttgart",
  "Suai",
  "Sucre",
  "Suez",
  "Suharekë",
  "Suhum",
  "Sukkur",
  "Sukrah",
  "Sukth",
  "Sukuta",
  "Sulakyurt",
  "Sullana",
  "Sultanbeyli",
  "Sultandağı",
  "Sultanhanı",
  "Sultanhisar",
  "Suluova",
  "Sumba",
  "Sumbas",
  "Sumbawanga",
  "Sumbe",
  "Sumedang",
  "Sumqayıt",
  "Sunch’ŏn",
  "Sundsvall",
  "Sungai Petani",
  "Sungurlu",
  "Sunyani",
  "Suong",
  "Supaul",
  "Sur",
  "Surabaya",
  "Surat Thani",
  "Surinam",
  "Surrey",
  "Surt",
  "Suruç",
  "Susurluk",
  "Susuz",
  "Suva",
  "Suwon",
  "Suzak",
  "Suşehri",
  "Svay Rieng",
  "Sveti Nikole",
  "Swakopmund",
  "Swieqi",
  "Swords",
  "Sydney",
  "Sylhet",
  "Szczecin",
  "Szeged",
  "Szolnok",
  "Szombathely",
  "Székesfehérvár",
  "São Domingos",
  "São Filipe",
  "São João dos Angolares",
  "São Luís",
  "São Paulo",
  "São Tomé",
  "Ségou",
  "Sélibaby",
  "Sétif",
  "Södertälje",
  "Söke",
  "Söğüt",
  "Söğütlü",
  "Sühbaatar",
  "Sürmene",
  "Sütçüler",
  "Sındırgı",
  "Sŏngnam",
  "Sūrat",
  "Taastrup",
  "Tabarre",
  "Tabligbo",
  "Tabora",
  "Tabrīz",
  "Tabubil",
  "Tabūk",
  "Tacna",
  "Tacuarembó",
  "Tadjourah",
  "Taguig City",
  "Tahoua",
  "Taichung",
  "Tainan",
  "Taipei",
  "Taitung",
  "Takeo",
  "Talas",
  "Talas",
  "Talatona",
  "Talca",
  "Tallaght",
  "Tallinn",
  "Talsi",
  "Tamale",
  "Tambacounda",
  "Tampa",
  "Tampere",
  "Tanch’ŏn",
  "Tangerang",
  "Tangier",
  "Tanki Leendert",
  "Taourirt",
  "Taoyuan District",
  "Taranto",
  "Tarapoto",
  "Tarawa",
  "Taraz",
  "Tari",
  "Tarija",
  "Taro",
  "Tarrafal",
  "Tarrafal",
  "Tarsus",
  "Tartu",
  "Tarīm",
  "Tashkent",
  "Tasiilaq",
  "Tasiusaq",
  "Tatabánya",
  "Tataouine",
  "Tatvan",
  "Taunggyi",
  "Tauragė",
  "Tauranga",
  "Tavas",
  "Tavşanlı",
  "Taşkent",
  "Taşköprü",
  "Taşlıçay",
  "Taşova",
  "Taşucu",
  "Ta‘izz",
  "Tbilisi",
  "Tchaourou",
  "Tchibanga",
  "Tchibota",
  "Techiman",
  "Tefenni",
  "Tegucigalpa",
  "Tehran",
  "Tejen",
  "Tekirdağ",
  "Tekkeköy",
  "Tekman",
  "Tel Aviv-Yafo",
  "Tela",
  "Telavi",
  "Telšiai",
  "Tema",
  "Temara",
  "Temirtaū",
  "Temuco",
  "Tenkodogo",
  "Teplice",
  "Teresina",
  "Terme",
  "Termiz",
  "Teseney",
  "Tete",
  "Tetovo",
  "Teyateyaneng",
  "Tešanj",
  "Thakhèk",
  "Thamaga",
  "Thanh Hóa",
  "Thanhlyin",
  "The Bottom",
  "The Hague",
  "The Valley",
  "Thessaloníki",
  "Thimphu",
  "Thinadhoo",
  "Thiès",
  "Thun",
  "Thái Nguyên",
  "Thủ Đức",
  "Tianjin",
  "Tiaret",
  "Tidjikja",
  "Tigoa",
  "Tijuana",
  "Tiko",
  "Tilburg",
  "Tillabéri",
  "Timbedgha",
  "Timişoara",
  "Tin Shui Wai",
  "Tipitapa",
  "Tirana",
  "Tiraspol",
  "Tire",
  "Tirebolu",
  "Titao",
  "Tivaouane",
  "Tivat",
  "Tlemcen",
  "Tlokweng",
  "Toamasina",
  "Tobruk",
  "Tocoa",
  "Tocumen",
  "Tofol",
  "Toftir",
  "Tokat",
  "Tokha",
  "Tokmok",
  "Tokyo",
  "Toliara",
  "Tolyatti",
  "Tomarza",
  "Tonacatepeque",
  "Tondo",
  "Tongjin",
  "Tongoma",
  "Tongshan",
  "Tonj",
  "Tonya",
  "Toowoomba",
  "Toprakkale",
  "Torbalı",
  "Torit",
  "Toronto",
  "Tortum",
  "Torul",
  "Toruń",
  "Tosya",
  "Totness",
  "Touba",
  "Toufen",
  "Tougué",
  "Toulon",
  "Toulouse",
  "Tournai",
  "Townsville",
  "Trabzon",
  "Tralee",
  "Trashi Yangtse",
  "Trashigang",
  "Travnik",
  "Trbovlje",
  "Trenčín",
  "Triesen",
  "Triesenberg",
  "Trieste",
  "Trincomalee",
  "Trindade",
  "Trinidad",
  "Tripoli",
  "Tripoli",
  "Trnava",
  "Trondheim",
  "Trongsa",
  "Trujillo",
  "Trujillo Alto",
  "Tsetserleg",
  "Tshikapa",
  "Tsimasham",
  "Tsing Yi Town",
  "Tsingoni",
  "Tskhinvali",
  "Tsumeb",
  "Tsévié",
  "Tubmanburg",
  "Tufanbeyli",
  "Tukums",
  "Tulagi",
  "Tunapuna",
  "Tunceli",
  "Tung Tau Tsuen",
  "Tungi",
  "Tunis",
  "Turgutalp",
  "Turgutlu",
  "Turhal",
  "Turin",
  "Turku",
  "Turmero",
  "Tursunzoda",
  "Tut",
  "Tutong",
  "Tuzi",
  "Tuzla",
  "Tuzla",
  "Tuzluca",
  "Tyre",
  "Tyumen",
  "Tân An",
  "Tân Uyên",
  "Târgu-Mureş",
  "Tébessa",
  "Télimélé",
  "Tétouan",
  "Tórshavn",
  "Tôlan̈aro",
  "Tömük",
  "Tønsberg",
  "Türkeli",
  "Türkistan",
  "Türkmenabat",
  "Türkmenbaşy",
  "Türkoğlu",
  "Tāluqān",
  "Tāngāil",
  "Ubon Ratchathani",
  "Ubungo",
  "Udon Thani",
  "Ufa",
  "Ukmergė",
  "Ula",
  "Ulaanbaatar",
  "Ulaangom",
  "Ulcinj",
  "Uliastay",
  "Ulsan",
  "Ulubey",
  "Uludere",
  "Ulukışla",
  "Ulus",
  "Umeå",
  "Umm Qurūn",
  "Umm al Qaywayn",
  "Umm Şalāl ‘Alī",
  "Umraniye",
  "Umurlu",
  "Ungheni",
  "Ungoofaaru",
  "Upernavik",
  "Upper Buchanan",
  "Upper Hutt",
  "Uppsala",
  "Uppsala",
  "Urganch",
  "Urla",
  "Uster",
  "Usulután",
  "Utena",
  "Utrecht",
  "Uummannaq",
  "Uvinza",
  "Uvira",
  "Uzundere",
  "Uzungöz",
  "Uzunköprü",
  "Uíge",
  "Uşak",
  "Užice",
  "Vaasa",
  "Vadodara",
  "Vaduz",
  "Vahdat",
  "Vailoa",
  "Vakfıkebir",
  "Valencia",
  "Valencia",
  "Valencia",
  "Valenzuela",
  "Valga",
  "Valjevo",
  "Valladolid",
  "Valledupar",
  "Valletta",
  "Valmiera",
  "Valparaíso",
  "Van",
  "Vanadzor",
  "Vancouver",
  "Vangviang",
  "Vanimo",
  "Vantaa",
  "Varaždin",
  "Varna",
  "Varto",
  "Vatican City",
  "Vaughan",
  "Vega Baja",
  "Vejle",
  "Velenje",
  "Veles",
  "Velika Gorica",
  "Veliko Tarnovo",
  "Velimeşe",
  "Venice",
  "Ventspils",
  "Vernier",
  "Verona",
  "Veszprém",
  "Veymandoo",
  "Vezirköprü",
  "Vianden",
  "Viborg",
  "Victoria",
  "Victoria",
  "Vienna",
  "Vientiane",
  "Vieux Fort",
  "Vigo",
  "Vihiga",
  "Vila Franca de Xira",
  "Vila Junqueiro",
  "Vila Nova de Gaia",
  "Vila Teixeira da Silva",
  "Viligili",
  "Viljandi",
  "Villa Canales",
  "Villa Curuguaty",
  "Villa Elisa",
  "Villa Nueva",
  "Villa Tunari",
  "Villach",
  "Villanueva",
  "Villavicencio",
  "Villeurbanne",
  "Vilnius",
  "Vinh",
  "Vinica",
  "Vinkovci",
  "Vinnytsia",
  "Viqueque",
  "Viranşehir",
  "Visaginas",
  "Vishākhapatnam",
  "Visoko",
  "Viti",
  "Vitoria-Gasteiz",
  "Vitsyebsk",
  "Vize",
  "Viðareiði",
  "Viña del Mar",
  "Vlorë",
  "Voinjama",
  "Volgograd",
  "Voronezh",
  "Vratsa",
  "Vreed-en-Hoop",
  "Vrhnika",
  "Vushtrri",
  "Vágur",
  "Västerås",
  "Vólos",
  "Võru",
  "Vũng Tàu",
  "Wa",
  "Wad Medani",
  "Wakiso",
  "Walvisbaai",
  "Wang Tau Hom",
  "Wangdue Phodrang",
  "Warnes",
  "Warsaw",
  "Washington",
  "Waterford",
  "Wau",
  "Wau",
  "Wellington",
  "Wels",
  "Weno",
  "West End",
  "Wewak",
  "Whanganui",
  "Whangarei",
  "Widekum",
  "Wiener Neustadt",
  "Willemstad",
  "Wiltz",
  "Windhoek",
  "Winnipeg",
  "Winterthur",
  "Wiwilí",
  "Wolfsberg",
  "Wollongong",
  "Worthing",
  "Wrocław",
  "Wuhan",
  "Wuppertal",
  "Wé",
  "Wŏnsan",
  "Xai",
  "Xai-Xai",
  "Xaignabouli",
  "Xam Nua",
  "Xankəndi",
  "Xiangkhoang",
  "Xiva",
  "Xi’an",
  "Xırdalan",
  "Yacuiba",
  "Yafran",
  "Yahyalı",
  "Yahşihan",
  "Yakacık",
  "Yakacık",
  "Yakakent",
  "Yakınca",
  "Yalova",
  "Yalvaç",
  "Yambio",
  "Yambol",
  "Yanbu",
  "Yanggok",
  "Yangmei",
  "Yao",
  "Yaoundé",
  "Yapraklı",
  "Yaren",
  "Yatağan",
  "Yattir",
  "Yauco",
  "Yavuzeli",
  "Yayladağı",
  "Yazd",
  "Yazıhan",
  "Yazıkonak",
  "Yağlıdere",
  "Ya‘bad",
  "Yei",
  "Yekaterinburg",
  "Yenice",
  "Yenice",
  "Yenice",
  "Yenimahalle",
  "Yenipazar",
  "Yeniçiftlik",
  "Yenişehir",
  "Yenişehir",
  "Yerevan",
  "Yerköy",
  "Yevlax",
  "Yeşilhisar",
  "Yeşilköy",
  "Yeşilli",
  "Yeşilova",
  "Yeşilyurt",
  "Yeşilyurt",
  "Yilan",
  "Yoboki",
  "Yokohama",
  "Yolöten",
  "Yomou",
  "Yomra",
  "Yopougon",
  "Yoro",
  "Yozgat",
  "Yuanlin",
  "Yukarıkaraman",
  "Yumurtalık",
  "Yunak",
  "Yusufeli",
  "Yüksekova",
  "Yüreğir",
  "Yıldırım",
  "Yıldız",
  "Yıldızeli",
  "Yığılca",
  "Zaanstad",
  "Zabīd",
  "Zacatecoluca",
  "Zadar",
  "Zagnanado",
  "Zagreb",
  "Zahlé",
  "Zalaegerszeg",
  "Zamboanga City",
  "Zanandore",
  "Zanzibar",
  "Zapopan",
  "Zaporizhzhia",
  "Zara",
  "Zaragoza",
  "Zaranj",
  "Zargar",
  "Zemio",
  "Zemun",
  "Zenica",
  "Zestaponi",
  "Zhangaözen",
  "Zhemgang",
  "Zhlobin",
  "Zhongli",
  "Zhoukou",
  "Zhubei",
  "Zielona Góra",
  "Ziguinchor",
  "Zile",
  "Zinder",
  "Zinjibār",
  "Zlín",
  "Zoetermeer",
  "Zomba",
  "Zonguldak",
  "Zouerate",
  "Zrenjanin",
  "Zugdidi",
  "Zuwārah",
  "Zvishavane",
  "Zvolen",
  "Zvornik",
  "Zwedru",
  "Zwolle",
  "Zégoua",
  "Zürich",
  "Zāhedān",
  "Ágios Athanásios",
  "Änew",
  "Ålesund",
  "Çal",
  "Çaldıran",
  "Çamardı",
  "Çamaş",
  "Çameli",
  "Çamlıyayla",
  "Çamoluk",
  "Çan",
  "Çanakkale",
  "Çankaya",
  "Çankırı",
  "Çanta",
  "Çarşamba",
  "Çarşıbaşı",
  "Çat",
  "Çatak",
  "Çatalca",
  "Çatalpınar",
  "Çavdır",
  "Çay",
  "Çaybaşı",
  "Çaycuma",
  "Çayeli",
  "Çaykara",
  "Çayıralan",
  "Çayırlı",
  "Çayırova",
  "Çağlayancerit",
  "Çekerek",
  "Çekme",
  "Çeltik",
  "Çerkezköy",
  "Çerkeş",
  "Çermik",
  "Çeşme",
  "Çifteler",
  "Çiftlik",
  "Çiftlikköy",
  "Çilimli",
  "Çine",
  "Çivril",
  "Çiçekdağı",
  "Çiğli",
  "Çobanlar",
  "Çorlu",
  "Çorum",
  "Çubuk",
  "Çukurca",
  "Çukurçayır",
  "Çumra",
  "Çüngüş",
  "Çıldır",
  "Çınar",
  "Çınarcık",
  "Érd",
  "Évosmos",
  "Ílion",
  "Ísafjörður",
  "Ñemby",
  "Ödemiş",
  "Ölgiy",
  "Ömerli",
  "Öndörhaan",
  "Örebro",
  "Öskemen",
  "Özalp",
  "Özdere",
  "Özgön",
  "Ústí nad Labem",
  "Ünye",
  "Ürgüp",
  "Üzümlü",
  "Ārba Minch’",
  "Āwasa",
  "Čakovec",
  "Čačak",
  "České Budějovice",
  "Đà Lạt",
  "Ērer Sātā",
  "Īṭahari̇̄",
  "İdil",
  "İhsaniye",
  "İkizce",
  "İliç",
  "İmamoğlu",
  "İncesu",
  "İncirliova",
  "İnebolu",
  "İnegöl",
  "İpsala",
  "İskenderun",
  "İskilip",
  "İslahiye",
  "İspir",
  "İvrindi",
  "İzmir",
  "İznik",
  "Łódź",
  "Ōsaka",
  "Ōta-ku",
  "Şabanözü",
  "Şabrātah",
  "Şabyā",
  "Şalpazarı",
  "Şalālah",
  "Şanlıurfa",
  "Şarkîkaraağaç",
  "Şarköy",
  "Şarkışla",
  "Şatrovka",
  "Şavşat",
  "Şa‘dah",
  "Şebin Karahisar",
  "Şefaatlı",
  "Şemdinli",
  "Şenkaya",
  "Şereflikoçhisar",
  "Şile",
  "Şiran",
  "Şirvan",
  "Şirvan",
  "Şuhut",
  "Şırnak",
  "Şəki",
  "Şəmkir",
  "Šabac",
  "Šiauliai",
  "Šibenik",
  "Šilutė",
  "Škofja Loka",
  "Štip",
  "Ţarţūs",
  "Ţūkh",
  "Ţūlkarm",
  "Żabbar",
  "Żebbuġ",
  "Żejtun",
  "Żurrieq",
  "Žilina",
  "Živinice",
  "Ḩafr al Bāţin",
  "Ḩajjah",
  "Ḩalwān",
  "Ḩamāh",
  "Ḩā’il",
  "‘Abasān al Kabīrah",
  "‘Ajlūn",
  "‘Ajmān",
  "‘Ibrī",
  "’s-Hertogenbosch"
  ]; // Array to hold cities

const ChartThree: React.FC = () => {
  const [state, setState] = useState<ChartThreeState>({
    series: [],
    days: [],
  });
  const [selectedCity, setSelectedCity] = useState<string>(cities[0]); // Update to use cities directly

  useEffect(() => {
    fetchWeatherData(selectedCity);
  }, [selectedCity]);

  const fetchWeatherData = async (city: string) => {
    try {
      const response = await axios.get(
        `https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/${city}?include=fcst%2Cobs%2Chistfcst%2Cstats%2Cdays%2Chours%2Ccurrent%2Calerts&key=XMJF54BDVDFY3YXBQ84UE6P6A&options=beta&contentType=json`
      );
      const forecast = response.data.days;
      const visibilityData = forecast.map((day: any) => day.visibility); // Extract visibility distance
      const days = forecast.map((day: any) => {
        const date = new Date(day.datetime);
        return `${date.toLocaleString("en", { month: "short" })} ${date.getDate()}`;
      });
      setState({ series: visibilityData, days });
    } catch (error) {
      console.error("Error fetching weather data:", error);
    }
  };

  const handleCityChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    setSelectedCity(e.target.value);
  };

  return (
    <div className="col-span-12 rounded-sm border border-stroke bg-white px-5 pb-5 pt-7.5 shadow-default dark:border-strokedark dark:bg-boxdark sm:px-7.5 xl:col-span-5">
      <div className="mb-3 justify-between gap-4 sm:flex">
        <div>
          <h5 className="text-lg font-semibold text-black dark:text-white"> {/* Updated text size */}
            Visibility Distance (15 Days)
          </h5>
        </div>
        <div className="flex">
          <select
            className="px-1 py-1 border rounded text-xs mb-2"
            style={{ width: '100px' }} // Inline style for fixed width
            value={selectedCity}
            onChange={handleCityChange}
          >
            {cities.map((city) => (
              <option key={city} value={city}>
                {city}
              </option>
            ))}
          </select>
        </div>
      </div>

      <div className="mb-2">
        <div id="chartThree" className="mx-auto flex justify-center">
          <ReactApexChart
            options={{
              ...options,
              xaxis: {
                categories: state.days,
              },
            }}
            series={[{ name: "Visibility Distance", data: state.series }]}
            type="line"
          />
        </div>
      </div>

      <div className="-mx-8 flex flex-wrap items-center justify-center gap-y-3">
        {state.series.map((visibility, index) => (
          <div className="w-full px-8 sm:w-1/2" key={index}>
            <div className="flex w-full items-center">
              <p className="flex w-full justify-between text-sm font-medium text-black dark:text-white">
                <span style={{ width: "60px" }}>
                  {state.days[index]}
                </span>
                <span>{visibility} km</span> {/* Adjusted for visibility in kilometers */}
              </p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default ChartThree;