from .base import db
from .flight import Flight
from .airport import Airport
from .aircraft_type import AircraftType
from .seat_map import SeatMap
from .pilot import Pilot
from .cabin_crew import CabinCrew
from .passenger import Passenger
from .seat_assignment import FlightSeatAssignment
